import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  CheckCircle,
  ArrowLeft,
  FileText,
  Mail,
  Database,
  Workflow,
  Download,
  Eye,
  X,
  Building2,
  Calendar,
  MapPin,
  Phone,
  Globe,
  DollarSign,
  Award,
  Shield,
  Copy,
  ExternalLink
} from 'lucide-react';

const OutputsPage = () => {
  const navigate = useNavigate();
  const [selectedOutput, setSelectedOutput] = useState<string | null>(null);

  const outputs = [
    {
      id: 'registration-form',
      title: 'Auto-Generated Registration Form',
      category: 'Form Generation',
      icon: FileText,
      color: 'from-green-500 to-emerald-500',
      description: 'Complete supplier registration form with validation',
      generatedBy: 'Microsoft Copilot + Forms',
      timeToGenerate: 'Instant'
    },
    {
      id: 'approval-email',
      title: 'Automated Notification Email',
      category: 'Email Template',
      icon: Mail,
      color: 'from-blue-500 to-cyan-500',
      description: 'Personalized approval email with all details',
      generatedBy: 'Power Automate + Copilot',
      timeToGenerate: 'Instant'
    },
    {
      id: 'extracted-data',
      title: 'Structured Data Extraction',
      category: 'Data Processing',
      icon: Database,
      color: 'from-purple-500 to-pink-500',
      description: 'JSON data extracted from uploaded documents',
      generatedBy: 'Copilot AI + OCR',
      timeToGenerate: '2 seconds'
    },
    {
      id: 'workflow-diagram',
      title: 'Approval Workflow Visualization',
      category: 'Workflow Automation',
      icon: Workflow,
      color: 'from-orange-500 to-red-500',
      description: 'Visual workflow with stages and assignments',
      generatedBy: 'Power Automate',
      timeToGenerate: 'Instant'
    },
    {
      id: 'registration-certificate',
      title: 'Registration Certificate',
      category: 'Document Generation',
      icon: Award,
      color: 'from-indigo-500 to-purple-500',
      description: 'Official certificate with digital signature',
      generatedBy: 'Copilot + Power Automate',
      timeToGenerate: 'Instant'
    },
    {
      id: 'document-summary',
      title: 'AI Document Summary',
      category: 'Document Analysis',
      icon: FileText,
      color: 'from-cyan-500 to-blue-500',
      description: 'Intelligent summary of uploaded documents',
      generatedBy: 'Copilot AI',
      timeToGenerate: '3 seconds'
    }
  ];

  const renderOutputContent = (outputId: string) => {
    switch(outputId) {
      case 'registration-form':
        return (
          <div className="bg-white p-8 rounded-xl">
            <div className="border-4 border-green-600 rounded-xl p-8 bg-gradient-to-br from-green-50 to-emerald-50">
              {/* Form Header */}
              <div className="text-center mb-8 border-b-2 border-green-600 pb-6">
                <div className="flex items-center justify-center mb-4">
                  <Building2 className="w-12 h-12 text-green-600" />
                </div>
                <h2 className="text-3xl font-bold text-gray-900 mb-2">
                  Department of Land Reform & Rural Development
                </h2>
                <h3 className="text-xl font-semibold text-green-600">
                  Supplier Registration Form
                </h3>
                <p className="text-sm text-gray-600 mt-2">
                  Auto-Generated by Microsoft Copilot • Form ID: SRF-2025-001234
                </p>
              </div>

              {/* Form Content */}
              <div className="space-y-6">
                {/* Company Information */}
                <div className="bg-white rounded-lg p-6 border-2 border-green-200">
                  <h4 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                    <Building2 className="w-5 h-5 text-green-600 mr-2" />
                    Company Information
                  </h4>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Legal Name</label>
                      <p className="text-gray-900 mt-1">Agri-Solutions Pty Ltd</p>
                    </div>
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Registration Number</label>
                      <p className="text-gray-900 mt-1">2019/123456/07</p>
                    </div>
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Tax Number</label>
                      <p className="text-gray-900 mt-1">9876543210</p>
                    </div>
                    <div>
                      <label className="text-sm font-semibold text-gray-700">BEE Level</label>
                      <p className="text-gray-900 mt-1">Level 2 Contributor</p>
                    </div>
                  </div>
                </div>

                {/* Contact Details */}
                <div className="bg-white rounded-lg p-6 border-2 border-blue-200">
                  <h4 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                    <Phone className="w-5 h-5 text-blue-600 mr-2" />
                    Contact Details
                  </h4>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Primary Contact</label>
                      <p className="text-gray-900 mt-1">Thabo Maseko (CEO)</p>
                    </div>
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Phone</label>
                      <p className="text-gray-900 mt-1">+27 11 234 5678</p>
                    </div>
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Email</label>
                      <p className="text-gray-900 mt-1">thabo@agrisolutions.co.za</p>
                    </div>
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Website</label>
                      <p className="text-gray-900 mt-1">www.agrisolutions.co.za</p>
                    </div>
                  </div>
                  <div className="mt-4">
                    <label className="text-sm font-semibold text-gray-700">Physical Address</label>
                    <p className="text-gray-900 mt-1">123 Farm Road, Pretoria, Gauteng, 0001</p>
                  </div>
                </div>

                {/* Banking Information */}
                <div className="bg-white rounded-lg p-6 border-2 border-purple-200">
                  <h4 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                    <DollarSign className="w-5 h-5 text-purple-600 mr-2" />
                    Banking Information
                  </h4>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Bank Name</label>
                      <p className="text-gray-900 mt-1">First National Bank</p>
                    </div>
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Account Number</label>
                      <p className="text-gray-900 mt-1">62012345678</p>
                    </div>
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Branch Code</label>
                      <p className="text-gray-900 mt-1">250655</p>
                    </div>
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Account Type</label>
                      <p className="text-gray-900 mt-1">Business Cheque</p>
                    </div>
                  </div>
                </div>

                {/* Service Offerings */}
                <div className="bg-white rounded-lg p-6 border-2 border-orange-200">
                  <h4 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                    <Award className="w-5 h-5 text-orange-600 mr-2" />
                    Service Offerings
                  </h4>
                  <div className="space-y-3">
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Primary Category</label>
                      <p className="text-gray-900 mt-1">Agricultural Equipment</p>
                    </div>
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Subcategories</label>
                      <div className="flex flex-wrap gap-2 mt-2">
                        <span className="bg-orange-100 text-orange-700 px-3 py-1 rounded-full text-sm">Tractors</span>
                        <span className="bg-orange-100 text-orange-700 px-3 py-1 rounded-full text-sm">Irrigation Systems</span>
                        <span className="bg-orange-100 text-orange-700 px-3 py-1 rounded-full text-sm">Harvesting Equipment</span>
                      </div>
                    </div>
                    <div>
                      <label className="text-sm font-semibold text-gray-700">Geographic Coverage</label>
                      <div className="flex flex-wrap gap-2 mt-2">
                        <span className="bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-sm">Gauteng</span>
                        <span className="bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-sm">Limpopo</span>
                        <span className="bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-sm">Mpumalanga</span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Compliance Documents */}
                <div className="bg-white rounded-lg p-6 border-2 border-indigo-200">
                  <h4 className="text-lg font-bold text-gray-900 mb-4 flex items-center">
                    <Shield className="w-5 h-5 text-indigo-600 mr-2" />
                    Compliance Documents
                  </h4>
                  <div className="space-y-2">
                    <div className="flex items-center justify-between p-3 bg-green-50 rounded-lg">
                      <div className="flex items-center space-x-2">
                        <CheckCircle className="w-5 h-5 text-green-600" />
                        <span className="text-sm font-semibold">Tax Clearance Certificate</span>
                      </div>
                      <span className="text-xs text-green-700 bg-green-100 px-2 py-1 rounded">Valid</span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-green-50 rounded-lg">
                      <div className="flex items-center space-x-2">
                        <CheckCircle className="w-5 h-5 text-green-600" />
                        <span className="text-sm font-semibold">BEE Certificate</span>
                      </div>
                      <span className="text-xs text-green-700 bg-green-100 px-2 py-1 rounded">Valid</span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-green-50 rounded-lg">
                      <div className="flex items-center space-x-2">
                        <CheckCircle className="w-5 h-5 text-green-600" />
                        <span className="text-sm font-semibold">Company Registration</span>
                      </div>
                      <span className="text-xs text-green-700 bg-green-100 px-2 py-1 rounded">Verified</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Form Footer */}
              <div className="mt-8 pt-6 border-t-2 border-green-600">
                <div className="flex items-center justify-between text-sm text-gray-600">
                  <div className="flex items-center space-x-2">
                    <Calendar className="w-4 h-4" />
                    <span>Generated: 02 December 2025, 09:34 AM</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <CheckCircle className="w-4 h-4 text-green-600" />
                    <span className="text-green-600 font-semibold">Auto-Validated</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case 'approval-email':
        return (
          <div className="bg-white p-8 rounded-xl">
            <div className="border-2 border-blue-300 rounded-xl overflow-hidden">
              {/* Email Header */}
              <div className="bg-gradient-to-r from-blue-600 to-cyan-600 text-white p-6">
                <div className="flex items-center space-x-3 mb-4">
                  <Mail className="w-8 h-8" />
                  <div>
                    <h3 className="font-bold text-lg">Automated Email Notification</h3>
                    <p className="text-sm text-blue-100">Generated by Power Automate + Copilot</p>
                  </div>
                </div>
              </div>

              {/* Email Metadata */}
              <div className="bg-gray-50 p-4 border-b-2 border-gray-200">
                <div className="space-y-2 text-sm">
                  <div className="flex">
                    <span className="font-semibold w-20 text-gray-700">From:</span>
                    <span className="text-gray-900">DLRRD Supplier Registration &lt;registration@dlrrd.gov.za&gt;</span>
                  </div>
                  <div className="flex">
                    <span className="font-semibold w-20 text-gray-700">To:</span>
                    <span className="text-gray-900">thabo@agrisolutions.co.za</span>
                  </div>
                  <div className="flex">
                    <span className="font-semibold w-20 text-gray-700">Subject:</span>
                    <span className="text-gray-900 font-semibold">✓ Supplier Registration Approved - Agri-Solutions Pty Ltd</span>
                  </div>
                  <div className="flex">
                    <span className="font-semibold w-20 text-gray-700">Date:</span>
                    <span className="text-gray-900">02 December 2025, 10:15 AM</span>
                  </div>
                </div>
              </div>

              {/* Email Body */}
              <div className="p-8 bg-white">
                <div className="space-y-4">
                  <p className="text-gray-900">Dear Thabo Maseko,</p>
                  
                  <p className="text-gray-900">
                    We are pleased to inform you that <strong>Agri-Solutions Pty Ltd</strong> has been 
                    successfully approved as a registered supplier for the Department of Land Reform and 
                    Rural Development.
                  </p>

                  <div className="bg-green-50 border-l-4 border-green-600 p-4 my-6">
                    <div className="flex items-center space-x-2 mb-2">
                      <CheckCircle className="w-5 h-5 text-green-600" />
                      <span className="font-bold text-green-900">Registration Details</span>
                    </div>
                    <div className="ml-7 space-y-1 text-sm">
                      <p><strong>Supplier ID:</strong> DLRRD-SUP-2025-001234</p>
                      <p><strong>Registration Date:</strong> 02 December 2025</p>
                      <p><strong>Category:</strong> Agricultural Equipment</p>
                      <p><strong>BEE Level:</strong> Level 2 Contributor</p>
                      <p><strong>Status:</strong> <span className="text-green-600 font-semibold">Active</span></p>
                    </div>
                  </div>

                  <p className="text-gray-900">
                    <strong>Next Steps:</strong>
                  </p>
                  <ul className="list-disc list-inside space-y-2 text-gray-900 ml-4">
                    <li>Your registration certificate is attached to this email</li>
                    <li>You can now participate in DLRRD tender opportunities</li>
                    <li>Access your supplier portal at: 
                      <a href="#" className="text-blue-600 underline ml-1">portal.dlrrd.gov.za</a>
                    </li>
                    <li>Review current tender opportunities in your category</li>
                  </ul>

                  <div className="bg-blue-50 border-l-4 border-blue-600 p-4 my-6">
                    <p className="text-sm text-blue-900">
                      <strong>📋 Important:</strong> Please ensure your compliance documents remain valid. 
                      You will receive automated reminders 30 days before any document expiry.
                    </p>
                  </div>

                  <p className="text-gray-900">
                    Should you have any questions, please contact our Supplier Relations team at 
                    <strong> suppliers@dlrrd.gov.za</strong> or call <strong>012 345 6789</strong>.
                  </p>

                  <p className="text-gray-900">
                    We look forward to a successful partnership.
                  </p>

                  <div className="mt-6 pt-6 border-t-2 border-gray-200">
                    <p className="text-gray-900 font-semibold">Best regards,</p>
                    <p className="text-gray-900">Supplier Registration Team</p>
                    <p className="text-gray-700 text-sm">Department of Land Reform and Rural Development</p>
                    <p className="text-gray-600 text-sm mt-2">📞 012 345 6789 | 📧 registration@dlrrd.gov.za</p>
                  </div>
                </div>
              </div>

              {/* Email Footer */}
              <div className="bg-gray-100 p-4 text-xs text-gray-600">
                <p>
                  🤖 This email was automatically generated by Microsoft Power Automate with Copilot AI. 
                  Please do not reply directly to this email.
                </p>
              </div>
            </div>
          </div>
        );

      case 'extracted-data':
        return (
          <div className="bg-white p-8 rounded-xl">
            <div className="border-2 border-purple-300 rounded-xl overflow-hidden">
              {/* Header */}
              <div className="bg-gradient-to-r from-purple-600 to-pink-600 text-white p-6">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <Database className="w-8 h-8" />
                    <div>
                      <h3 className="font-bold text-lg">Extracted Structured Data</h3>
                      <p className="text-sm text-purple-100">AI-Powered Data Extraction from Documents</p>
                    </div>
                  </div>
                  <button className="flex items-center space-x-2 bg-white/20 hover:bg-white/30 px-4 py-2 rounded-lg transition-colors">
                    <Copy className="w-4 h-4" />
                    <span className="text-sm">Copy JSON</span>
                  </button>
                </div>
              </div>

              {/* JSON Content */}
              <div className="bg-gray-900 p-6 overflow-x-auto">
                <pre className="text-green-400 text-sm font-mono">
{`{
  "supplierRegistration": {
    "metadata": {
      "extractionDate": "2025-12-02T09:34:21Z",
      "confidence": 98.7,
      "documentsProcessed": 5,
      "processingTime": "2.3s"
    },
    "companyInformation": {
      "legalName": "Agri-Solutions Pty Ltd",
      "registrationNumber": "2019/123456/07",
      "registrationDate": "2019-03-15",
      "taxNumber": "9876543210",
      "vatRegistered": true,
      "companyType": "Private Company",
      "status": "Active"
    },
    "contactDetails": {
      "primaryContact": {
        "name": "Thabo Maseko",
        "position": "Chief Executive Officer",
        "email": "thabo@agrisolutions.co.za",
        "phone": "+27112345678",
        "mobile": "+27821234567"
      },
      "physicalAddress": {
        "street": "123 Farm Road",
        "city": "Pretoria",
        "province": "Gauteng",
        "postalCode": "0001",
        "country": "South Africa"
      },
      "postalAddress": {
        "poBox": "PO Box 5678",
        "city": "Pretoria",
        "postalCode": "0002"
      },
      "website": "www.agrisolutions.co.za"
    },
    "bankingInformation": {
      "bankName": "First National Bank",
      "accountNumber": "62012345678",
      "accountType": "Business Cheque Account",
      "branchCode": "250655",
      "branchName": "Sandton City",
      "verified": true,
      "verificationDate": "2025-12-01"
    },
    "beeInformation": {
      "certificateNumber": "BEE-2024-789012",
      "level": 2,
      "contributor": "Level 2 Contributor",
      "points": 118.5,
      "issuedDate": "2024-07-01",
      "expiryDate": "2026-06-30",
      "status": "Valid",
      "verificationAgency": "BEE Verification Agency (Pty) Ltd"
    },
    "complianceDocuments": {
      "taxClearance": {
        "certificateNumber": "TAX-2025-456789",
        "status": "Valid",
        "issuedDate": "2025-06-15",
        "expiryDate": "2025-12-15",
        "verified": true
      },
      "registrationCertificate": {
        "cipro": "2019/123456/07",
        "verified": true,
        "verificationDate": "2025-12-01"
      },
      "insuranceCertificate": {
        "provider": "Santam Insurance",
        "policyNumber": "INS-2025-987654",
        "coverage": "R10,000,000",
        "expiryDate": "2026-03-31",
        "status": "Valid"
      }
    },
    "serviceOfferings": {
      "primaryCategory": "Agricultural Equipment",
      "subcategories": [
        "Tractors and Farming Machinery",
        "Irrigation Systems",
        "Harvesting Equipment"
      ],
      "geographicCoverage": [
        "Gauteng",
        "Limpopo",
        "Mpumalanga"
      ],
      "annualTurnover": "R15,000,000",
      "employeeCount": 45,
      "yearsInBusiness": 6
    },
    "riskAssessment": {
      "overallRisk": "Low",
      "creditScore": 785,
      "complianceScore": 98,
      "financialHealth": "Excellent",
      "recommendedCreditLimit": "R2,000,000",
      "approvalRecommendation": "Approved"
    },
    "approvalWorkflow": {
      "submissionDate": "2025-11-28T14:30:00Z",
      "regionalManagerApproval": {
        "approved": true,
        "approver": "John Smith",
        "date": "2025-11-29T10:15:00Z"
      },
      "complianceOfficerApproval": {
        "approved": true,
        "approver": "Sarah Johnson",
        "date": "2025-12-01T11:45:00Z"
      },
      "directorApproval": {
        "approved": true,
        "approver": "Dr. Michael Ndlovu",
        "date": "2025-12-02T09:30:00Z"
      },
      "finalStatus": "Approved",
      "supplierID": "DLRRD-SUP-2025-001234",
      "activationDate": "2025-12-02"
    }
  }
}`}
                </pre>
              </div>

              {/* Footer Info */}
              <div className="bg-purple-50 p-4">
                <div className="grid grid-cols-4 gap-4 text-center">
                  <div>
                    <p className="text-2xl font-bold text-purple-600">98.7%</p>
                    <p className="text-xs text-gray-600">Extraction Accuracy</p>
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-purple-600">2.3s</p>
                    <p className="text-xs text-gray-600">Processing Time</p>
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-purple-600">5</p>
                    <p className="text-xs text-gray-600">Documents Processed</p>
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-purple-600">24</p>
                    <p className="text-xs text-gray-600">Fields Extracted</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case 'workflow-diagram':
        return (
          <div className="bg-white p-8 rounded-xl">
            <div className="border-2 border-orange-300 rounded-xl overflow-hidden">
              {/* Header */}
              <div className="bg-gradient-to-r from-orange-600 to-red-600 text-white p-6">
                <div className="flex items-center space-x-3">
                  <Workflow className="w-8 h-8" />
                  <div>
                    <h3 className="font-bold text-lg">Automated Approval Workflow</h3>
                    <p className="text-sm text-orange-100">4-Stage Intelligent Routing</p>
                  </div>
                </div>
              </div>

              {/* Workflow Visual */}
              <div className="p-8 bg-gradient-to-br from-orange-50 to-red-50">
                <div className="relative">
                  {/* Connection Line */}
                  <div className="absolute top-20 left-0 right-0 h-1 bg-gradient-to-r from-blue-300 via-green-300 to-purple-300 hidden lg:block" style={{width: '85%', left: '7.5%'}}></div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-6 relative">
                    {/* Stage 1 */}
                    <div className="relative">
                      <div className="bg-white rounded-xl shadow-lg p-6 border-2 border-blue-500">
                        <div className="w-12 h-12 mx-auto mb-4 rounded-full bg-blue-500 flex items-center justify-center text-white font-bold text-xl">
                          1
                        </div>
                        <h4 className="font-bold text-center text-gray-900 mb-2">Auto-Validation</h4>
                        <div className="space-y-2 text-sm">
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">Document check</span>
                          </div>
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">Data validation</span>
                          </div>
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">Duplicate check</span>
                          </div>
                        </div>
                        <div className="mt-4 pt-4 border-t text-center">
                          <p className="text-xs text-gray-600">Assignee</p>
                          <p className="text-sm font-semibold text-gray-900">System</p>
                          <p className="text-xs text-blue-600 mt-1">⚡ Instant</p>
                        </div>
                        <div className="mt-3 bg-green-100 text-green-700 text-xs font-semibold py-1 px-3 rounded-full text-center">
                          ✓ Completed
                        </div>
                      </div>
                    </div>

                    {/* Stage 2 */}
                    <div className="relative">
                      <div className="bg-white rounded-xl shadow-lg p-6 border-2 border-green-500">
                        <div className="w-12 h-12 mx-auto mb-4 rounded-full bg-green-500 flex items-center justify-center text-white font-bold text-xl">
                          2
                        </div>
                        <h4 className="font-bold text-center text-gray-900 mb-2">Regional Review</h4>
                        <div className="space-y-2 text-sm">
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">Info review</span>
                          </div>
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">Doc verification</span>
                          </div>
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">Approval</span>
                          </div>
                        </div>
                        <div className="mt-4 pt-4 border-t text-center">
                          <p className="text-xs text-gray-600">Assignee</p>
                          <p className="text-sm font-semibold text-gray-900">John Smith</p>
                          <p className="text-xs text-green-600 mt-1">⏱ 1 day</p>
                        </div>
                        <div className="mt-3 bg-green-100 text-green-700 text-xs font-semibold py-1 px-3 rounded-full text-center">
                          ✓ Approved
                        </div>
                      </div>
                    </div>

                    {/* Stage 3 */}
                    <div className="relative">
                      <div className="bg-white rounded-xl shadow-lg p-6 border-2 border-yellow-500">
                        <div className="w-12 h-12 mx-auto mb-4 rounded-full bg-yellow-500 flex items-center justify-center text-white font-bold text-xl">
                          3
                        </div>
                        <h4 className="font-bold text-center text-gray-900 mb-2">Compliance Check</h4>
                        <div className="space-y-2 text-sm">
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">BEE verification</span>
                          </div>
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">Tax clearance</span>
                          </div>
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">Banking check</span>
                          </div>
                        </div>
                        <div className="mt-4 pt-4 border-t text-center">
                          <p className="text-xs text-gray-600">Assignee</p>
                          <p className="text-sm font-semibold text-gray-900">Sarah Johnson</p>
                          <p className="text-xs text-yellow-600 mt-1">⏱ 2 days</p>
                        </div>
                        <div className="mt-3 bg-green-100 text-green-700 text-xs font-semibold py-1 px-3 rounded-full text-center">
                          ✓ Verified
                        </div>
                      </div>
                    </div>

                    {/* Stage 4 */}
                    <div className="relative">
                      <div className="bg-white rounded-xl shadow-lg p-6 border-2 border-purple-500">
                        <div className="w-12 h-12 mx-auto mb-4 rounded-full bg-purple-500 flex items-center justify-center text-white font-bold text-xl">
                          4
                        </div>
                        <h4 className="font-bold text-center text-gray-900 mb-2">Final Approval</h4>
                        <div className="space-y-2 text-sm">
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">Final review</span>
                          </div>
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">Authorization</span>
                          </div>
                          <div className="flex items-center space-x-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-gray-700">Activation</span>
                          </div>
                        </div>
                        <div className="mt-4 pt-4 border-t text-center">
                          <p className="text-xs text-gray-600">Assignee</p>
                          <p className="text-sm font-semibold text-gray-900">Dr. M. Ndlovu</p>
                          <p className="text-xs text-purple-600 mt-1">⏱ 1 day</p>
                        </div>
                        <div className="mt-3 bg-green-100 text-green-700 text-xs font-semibold py-1 px-3 rounded-full text-center">
                          ✓ Approved
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Workflow Summary */}
                <div className="mt-8 bg-white rounded-xl shadow-lg p-6 border-2 border-green-500">
                  <div className="text-center">
                    <CheckCircle className="w-12 h-12 text-green-600 mx-auto mb-3" />
                    <h4 className="text-xl font-bold text-gray-900 mb-2">Workflow Completed</h4>
                    <p className="text-sm text-gray-600 mb-4">Total Processing Time: 4 business days</p>
                    <div className="flex items-center justify-center space-x-6 text-sm">
                      <div>
                        <p className="font-bold text-green-600">100%</p>
                        <p className="text-gray-600">Completion Rate</p>
                      </div>
                      <div>
                        <p className="font-bold text-blue-600">4/4</p>
                        <p className="text-gray-600">Stages Approved</p>
                      </div>
                      <div>
                        <p className="font-bold text-purple-600">0</p>
                        <p className="text-gray-600">Delays</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Features */}
              <div className="bg-orange-50 p-6">
                <h4 className="font-bold text-gray-900 mb-4">Workflow Features:</h4>
                <div className="grid grid-cols-3 gap-4">
                  <div className="flex items-start space-x-2">
                    <CheckCircle className="w-5 h-5 text-orange-600 flex-shrink-0" />
                    <div>
                      <p className="text-sm font-semibold text-gray-900">Auto-Notifications</p>
                      <p className="text-xs text-gray-600">Email + Teams alerts</p>
                    </div>
                  </div>
                  <div className="flex items-start space-x-2">
                    <CheckCircle className="w-5 h-5 text-orange-600 flex-shrink-0" />
                    <div>
                      <p className="text-sm font-semibold text-gray-900">Mobile Approvals</p>
                      <p className="text-xs text-gray-600">Approve anywhere</p>
                    </div>
                  </div>
                  <div className="flex items-start space-x-2">
                    <CheckCircle className="w-5 h-5 text-orange-600 flex-shrink-0" />
                    <div>
                      <p className="text-sm font-semibold text-gray-900">SLA Tracking</p>
                      <p className="text-xs text-gray-600">Auto-escalation</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case 'registration-certificate':
        return (
          <div className="bg-white p-8 rounded-xl">
            <div className="border-4 border-indigo-600 rounded-xl p-8 bg-gradient-to-br from-indigo-50 to-purple-50 relative overflow-hidden">
              {/* Watermark */}
              <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 opacity-5">
                <Award className="w-96 h-96 text-indigo-600" />
              </div>

              {/* Certificate Content */}
              <div className="relative z-10">
                {/* Header */}
                <div className="text-center mb-8 border-b-4 border-indigo-600 pb-6">
                  <div className="flex items-center justify-center mb-4">
                    <div className="bg-indigo-600 p-4 rounded-full">
                      <Award className="w-16 h-16 text-white" />
                    </div>
                  </div>
                  <h2 className="text-4xl font-bold text-gray-900 mb-2">
                    OFFICIAL REGISTRATION CERTIFICATE
                  </h2>
                  <p className="text-xl text-indigo-600 font-semibold">
                    Department of Land Reform & Rural Development
                  </p>
                  <p className="text-sm text-gray-600 mt-2">Republic of South Africa</p>
                </div>

                {/* Certificate Body */}
                <div className="text-center mb-8">
                  <p className="text-lg text-gray-700 mb-6">This is to certify that</p>
                  <h3 className="text-3xl font-bold text-indigo-600 mb-6">
                    Agri-Solutions Pty Ltd
                  </h3>
                  <p className="text-lg text-gray-700 mb-2">
                    has been officially registered as an approved supplier
                  </p>
                  <p className="text-lg text-gray-700 mb-8">
                    for the Department of Land Reform and Rural Development
                  </p>

                  {/* Details Box */}
                  <div className="bg-white rounded-xl shadow-lg p-6 border-2 border-indigo-200 max-w-2xl mx-auto mb-8">
                    <div className="grid grid-cols-2 gap-6 text-left">
                      <div>
                        <p className="text-sm font-semibold text-gray-600">Supplier ID</p>
                        <p className="text-lg font-bold text-gray-900">DLRRD-SUP-2025-001234</p>
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-gray-600">Registration Date</p>
                        <p className="text-lg font-bold text-gray-900">02 December 2025</p>
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-gray-600">Category</p>
                        <p className="text-lg font-bold text-gray-900">Agricultural Equipment</p>
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-gray-600">BEE Level</p>
                        <p className="text-lg font-bold text-gray-900">Level 2 Contributor</p>
                      </div>
                      <div className="col-span-2">
                        <p className="text-sm font-semibold text-gray-600">Geographic Coverage</p>
                        <p className="text-lg font-bold text-gray-900">Gauteng, Limpopo, Mpumalanga</p>
                      </div>
                    </div>
                  </div>

                  {/* Validity */}
                  <div className="bg-green-100 border-2 border-green-500 rounded-lg p-4 max-w-md mx-auto mb-8">
                    <div className="flex items-center justify-center space-x-2">
                      <CheckCircle className="w-6 h-6 text-green-600" />
                      <div>
                        <p className="font-bold text-green-900">Status: ACTIVE</p>
                        <p className="text-sm text-green-700">Valid from 02 December 2025</p>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Signatures */}
                <div className="grid grid-cols-2 gap-8 mb-8">
                  <div className="text-center">
                    <div className="border-t-2 border-gray-400 pt-2 mb-2">
                      <p className="font-bold text-gray-900">Dr. Michael Ndlovu</p>
                    </div>
                    <p className="text-sm text-gray-600">Director: Supplier Relations</p>
                    <p className="text-xs text-gray-500">DLRRD</p>
                  </div>
                  <div className="text-center">
                    <div className="border-t-2 border-gray-400 pt-2 mb-2">
                      <p className="font-bold text-gray-900">02 December 2025</p>
                    </div>
                    <p className="text-sm text-gray-600">Date of Issue</p>
                  </div>
                </div>

                {/* Digital Signature & QR */}
                <div className="border-t-4 border-indigo-600 pt-6">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <Shield className="w-8 h-8 text-indigo-600" />
                      <div className="text-left">
                        <p className="text-sm font-bold text-gray-900">Digitally Signed</p>
                        <p className="text-xs text-gray-600">Certificate ID: CERT-2025-001234-DS</p>
                      </div>
                    </div>
                    <div className="text-right">
                      <div className="w-24 h-24 bg-white border-2 border-gray-300 rounded-lg flex items-center justify-center">
                        <p className="text-xs text-gray-500">QR Code</p>
                      </div>
                      <p className="text-xs text-gray-500 mt-1">Scan to verify</p>
                    </div>
                  </div>
                </div>

                {/* Footer */}
                <div className="mt-6 text-center text-xs text-gray-500">
                  <p>🤖 Auto-generated by Microsoft Copilot + Power Automate</p>
                  <p className="mt-1">This is an official government document. Any tampering is punishable by law.</p>
                </div>
              </div>
            </div>
          </div>
        );

      case 'document-summary':
        return (
          <div className="bg-white p-8 rounded-xl">
            <div className="border-2 border-cyan-300 rounded-xl overflow-hidden">
              {/* Header */}
              <div className="bg-gradient-to-r from-cyan-600 to-blue-600 text-white p-6">
                <div className="flex items-center space-x-3">
                  <FileText className="w-8 h-8" />
                  <div>
                    <h3 className="font-bold text-lg">AI-Powered Document Summary</h3>
                    <p className="text-sm text-cyan-100">Intelligent Analysis by Microsoft Copilot</p>
                  </div>
                </div>
              </div>

              {/* Summary Content */}
              <div className="p-8">
                <div className="space-y-6">
                  {/* Document Info */}
                  <div className="bg-cyan-50 rounded-lg p-6 border-2 border-cyan-200">
                    <h4 className="font-bold text-gray-900 mb-4">Document Information</h4>
                    <div className="grid grid-cols-2 gap-4 text-sm">
                      <div>
                        <p className="text-gray-600">Supplier Name</p>
                        <p className="font-semibold text-gray-900">Agri-Solutions Pty Ltd</p>
                      </div>
                      <div>
                        <p className="text-gray-600">Document Type</p>
                        <p className="font-semibold text-gray-900">Tax Clearance Certificate</p>
                      </div>
                      <div>
                        <p className="text-gray-600">Analysis Date</p>
                        <p className="font-semibold text-gray-900">02 December 2025</p>
                      </div>
                      <div>
                        <p className="text-gray-600">Processing Time</p>
                        <p className="font-semibold text-gray-900">3 seconds</p>
                      </div>
                    </div>
                  </div>

                  {/* Key Findings */}
                  <div>
                    <h4 className="font-bold text-gray-900 mb-3 flex items-center">
                      <CheckCircle className="w-5 h-5 text-green-600 mr-2" />
                      Key Findings
                    </h4>
                    <div className="space-y-3">
                      <div className="flex items-start space-x-3 p-4 bg-green-50 rounded-lg border-l-4 border-green-600">
                        <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                        <div>
                          <p className="font-semibold text-gray-900">Tax Clearance Status: VALID</p>
                          <p className="text-sm text-gray-700 mt-1">
                            Certificate is active and in good standing until 15 December 2025
                          </p>
                        </div>
                      </div>

                      <div className="flex items-start space-x-3 p-4 bg-green-50 rounded-lg border-l-4 border-green-600">
                        <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                        <div>
                          <p className="font-semibold text-gray-900">Tax Number Verified</p>
                          <p className="text-sm text-gray-700 mt-1">
                            Tax number 9876543210 successfully verified against SARS database
                          </p>
                        </div>
                      </div>

                      <div className="flex items-start space-x-3 p-4 bg-green-50 rounded-lg border-l-4 border-green-600">
                        <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                        <div>
                          <p className="font-semibold text-gray-900">Compliance Requirements Met</p>
                          <p className="text-sm text-gray-700 mt-1">
                            All SARS requirements satisfied. No outstanding tax obligations detected
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Risk Assessment */}
                  <div className="bg-blue-50 rounded-lg p-6 border-2 border-blue-200">
                    <h4 className="font-bold text-gray-900 mb-4">Risk Assessment</h4>
                    <div className="grid grid-cols-3 gap-4">
                      <div className="text-center">
                        <div className="w-16 h-16 mx-auto mb-2 rounded-full bg-green-500 flex items-center justify-center">
                          <p className="text-2xl font-bold text-white">A</p>
                        </div>
                        <p className="text-sm font-semibold text-gray-900">Overall Grade</p>
                        <p className="text-xs text-gray-600">Low Risk</p>
                      </div>
                      <div className="text-center">
                        <div className="w-16 h-16 mx-auto mb-2 rounded-full bg-green-500 flex items-center justify-center">
                          <p className="text-2xl font-bold text-white">98</p>
                        </div>
                        <p className="text-sm font-semibold text-gray-900">Compliance Score</p>
                        <p className="text-xs text-gray-600">Excellent</p>
                      </div>
                      <div className="text-center">
                        <div className="w-16 h-16 mx-auto mb-2 rounded-full bg-green-500 flex items-center justify-center">
                          <CheckCircle className="w-8 h-8 text-white" />
                        </div>
                        <p className="text-sm font-semibold text-gray-900">Recommendation</p>
                        <p className="text-xs text-gray-600">Approve</p>
                      </div>
                    </div>
                  </div>

                  {/* Detailed Analysis */}
                  <div>
                    <h4 className="font-bold text-gray-900 mb-3">Detailed Analysis</h4>
                    <div className="prose prose-sm max-w-none text-gray-700">
                      <p>
                        The AI analysis of Agri-Solutions Pty Ltd's Tax Clearance Certificate reveals 
                        a financially compliant organization with excellent standing. The certificate, 
                        issued on 15 June 2025, confirms that the company has met all tax obligations 
                        and maintains good standing with the South African Revenue Service (SARS).
                      </p>
                      <p className="mt-3">
                        <strong>Key compliance indicators:</strong>
                      </p>
                      <ul className="list-disc list-inside space-y-1 mt-2">
                        <li>All tax returns filed on time for the past 3 years</li>
                        <li>No outstanding tax liabilities or penalties</li>
                        <li>VAT registration active and compliant</li>
                        <li>PAYE obligations up to date</li>
                        <li>No audit queries or investigations pending</li>
                      </ul>
                      <p className="mt-3">
                        <strong>Recommendation:</strong> Based on the comprehensive analysis, 
                        this supplier meets all tax compliance requirements for registration approval. 
                        The system recommends proceeding with supplier registration and scheduling 
                        a 6-month compliance review before certificate expiry.
                      </p>
                    </div>
                  </div>

                  {/* Next Steps */}
                  <div className="bg-gradient-to-r from-blue-50 to-cyan-50 rounded-lg p-6 border-2 border-blue-200">
                    <h4 className="font-bold text-gray-900 mb-3">Recommended Next Steps</h4>
                    <ol className="list-decimal list-inside space-y-2 text-sm text-gray-700">
                      <li>Proceed with registration approval</li>
                      <li>Schedule 6-month compliance review (June 2025)</li>
                      <li>Add to approved vendors database</li>
                      <li>Send automated reminder 30 days before certificate expiry</li>
                      <li>Enable supplier portal access</li>
                    </ol>
                  </div>
                </div>
              </div>

              {/* Footer */}
              <div className="bg-cyan-50 p-4 border-t-2 border-cyan-200">
                <div className="flex items-center justify-between text-sm">
                  <div className="flex items-center space-x-2 text-gray-600">
                    <FileText className="w-4 h-4" />
                    <span>Analysis completed by Microsoft Copilot AI</span>
                  </div>
                  <div className="flex items-center space-x-4">
                    <div className="text-right">
                      <p className="font-bold text-cyan-600">99.2%</p>
                      <p className="text-xs text-gray-600">Confidence</p>
                    </div>
                    <div className="text-right">
                      <p className="font-bold text-cyan-600">3.2s</p>
                      <p className="text-xs text-gray-600">Processing</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 via-emerald-50 to-teal-50">
      {/* Header */}
      <header className="bg-white shadow-md border-b-4 border-green-600">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <button onClick={() => navigate('/')} className="flex items-center space-x-2 text-gray-600 hover:text-gray-900 transition-colors">
              <ArrowLeft className="w-5 h-5" />
              <span className="font-semibold">Back to Home</span>
            </button>
            <div className="flex items-center space-x-2 bg-green-100 px-4 py-2 rounded-full">
              <CheckCircle className="w-5 h-5 text-green-600" />
              <span className="text-sm font-semibold text-green-700">Output Examples</span>
            </div>
          </div>
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-6 py-12">
        {/* Title Section */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center space-x-2 bg-green-100 text-green-700 px-4 py-2 rounded-full text-sm font-semibold mb-4">
            <CheckCircle className="w-4 h-4" />
            <span>Requirement #5: Generated Outputs</span>
          </div>
          <h1 className="text-5xl font-bold text-gray-900 mb-4">
            Output Examples
            <span className="block text-transparent bg-clip-text bg-gradient-to-r from-green-600 to-emerald-600 mt-2">
              AI-Generated Documents
            </span>
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            View examples of forms, certificates, emails, and structured data 
            automatically generated by Copilot.
          </p>
        </div>

        {/* Output Categories */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
          {outputs.map((output) => {
            const Icon = output.icon;
            return (
              <div
                key={output.id}
                onClick={() => setSelectedOutput(output.id)}
                className="group bg-white rounded-xl shadow-lg p-6 hover:shadow-2xl transition-all duration-300 cursor-pointer transform hover:-translate-y-1 border-2 border-transparent hover:border-green-500"
              >
                <div className={`w-16 h-16 mx-auto mb-4 rounded-xl bg-gradient-to-br ${output.color} flex items-center justify-center transform group-hover:scale-110 transition-transform`}>
                  <Icon className="w-8 h-8 text-white" />
                </div>
                <h3 className="text-xl font-bold text-gray-900 mb-2 text-center group-hover:text-green-600 transition-colors">
                  {output.title}
                </h3>
                <p className="text-xs text-gray-500 text-center mb-2">{output.category}</p>
                <p className="text-gray-600 text-sm mb-4 text-center">{output.description}</p>
                
                <div className="space-y-2 text-xs">
                  <div className="flex items-center justify-between p-2 bg-gray-50 rounded-lg">
                    <span className="text-gray-600">Generated by:</span>
                    <span className="font-semibold text-gray-900">{output.generatedBy}</span>
                  </div>
                  <div className="flex items-center justify-between p-2 bg-green-50 rounded-lg">
                    <span className="text-gray-600">Time:</span>
                    <span className="font-semibold text-green-700">{output.timeToGenerate}</span>
                  </div>
                </div>

                <button className="w-full mt-4 bg-gradient-to-r from-green-500 to-emerald-500 text-white px-4 py-2 rounded-lg font-semibold text-sm flex items-center justify-center space-x-2 hover:shadow-lg transition-shadow">
                  <Eye className="w-4 h-4" />
                  <span>View Full Output</span>
                </button>
              </div>
            );
          })}
        </div>

        {/* Benefits Section */}
        <div className="bg-gradient-to-br from-green-600 to-emerald-600 rounded-2xl p-8 text-white shadow-2xl mb-12">
          <h3 className="text-2xl font-bold text-center mb-6">Why These Outputs Matter</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="w-16 h-16 mx-auto mb-3 rounded-full bg-white/20 flex items-center justify-center">
                <CheckCircle className="w-8 h-8 text-white" />
              </div>
              <p className="font-bold mb-2">100% Accuracy</p>
              <p className="text-sm text-green-100">AI ensures consistent, error-free documents every time</p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 mx-auto mb-3 rounded-full bg-white/20 flex items-center justify-center">
                <Database className="w-8 h-8 text-white" />
              </div>
              <p className="font-bold mb-2">Instant Generation</p>
              <p className="text-sm text-green-100">Create documents in seconds, not hours or days</p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 mx-auto mb-3 rounded-full bg-white/20 flex items-center justify-center">
                <Workflow className="w-8 h-8 text-white" />
              </div>
              <p className="font-bold mb-2">Full Automation</p>
              <p className="text-sm text-green-100">Zero manual intervention from creation to delivery</p>
            </div>
          </div>
        </div>
      </div>

      {/* Modal for Full Output View */}
      {selectedOutput && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4 overflow-y-auto">
          <div className="bg-white rounded-2xl max-w-6xl w-full max-h-[90vh] overflow-y-auto relative">
            <div className="sticky top-0 bg-white z-10 flex items-center justify-between p-6 border-b-2 border-gray-200">
              <h2 className="text-2xl font-bold text-gray-900">
                {outputs.find(o => o.id === selectedOutput)?.title}
              </h2>
              <button
                onClick={() => setSelectedOutput(null)}
                className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
              >
                <X className="w-6 h-6 text-gray-600" />
              </button>
            </div>
            <div className="p-6">
              {renderOutputContent(selectedOutput)}
            </div>
            <div className="sticky bottom-0 bg-white border-t-2 border-gray-200 p-6 flex items-center justify-between">
              <div className="flex items-center space-x-4">
                <button className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
                  <Download className="w-4 h-4" />
                  <span>Download PDF</span>
                </button>
                <button className="flex items-center space-x-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors">
                  <Copy className="w-4 h-4" />
                  <span>Copy Content</span>
                </button>
                <button className="flex items-center space-x-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors">
                  <ExternalLink className="w-4 h-4" />
                  <span>Open in SharePoint</span>
                </button>
              </div>
              <button
                onClick={() => setSelectedOutput(null)}
                className="px-6 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-colors font-semibold"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Footer */}
      <footer className="bg-gray-900 text-white mt-16">
        <div className="max-w-7xl mx-auto px-6 py-6">
          <div className="flex items-center justify-between">
            <p className="text-sm text-gray-400">
              DLRRD Copilot Demo - Output Examples
            </p>
            <div className="flex items-center space-x-2 text-sm text-gray-400">
              <span>Step 5 of 6</span>
              <div className="w-32 h-2 bg-gray-700 rounded-full overflow-hidden">
                <div className="w-5/6 h-full bg-green-500"></div>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default OutputsPage;
