import React from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  CheckCircle,
  ArrowLeft,
  FileText,
  Mail,
  Database,
  Workflow,
  Download
} from 'lucide-react';

const OutputsPage = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 via-emerald-50 to-teal-50">
      {/* Header */}
      <header className="bg-white shadow-md border-b-4 border-green-600">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <button onClick={() => navigate('/')} className="flex items-center space-x-2 text-gray-600 hover:text-gray-900 transition-colors">
              <ArrowLeft className="w-5 h-5" />
              <span className="font-semibold">Back to Home</span>
            </button>
            <div className="flex items-center space-x-2 bg-green-100 px-4 py-2 rounded-full">
              <CheckCircle className="w-5 h-5 text-green-600" />
              <span className="text-sm font-semibold text-green-700">Output Examples</span>
            </div>
          </div>
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-6 py-12">
        {/* Title Section */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center space-x-2 bg-green-100 text-green-700 px-4 py-2 rounded-full text-sm font-semibold mb-4">
            <CheckCircle className="w-4 h-4" />
            <span>Requirement #5: Generated Outputs</span>
          </div>
          <h1 className="text-5xl font-bold text-gray-900 mb-4">
            Output Examples
            <span className="block text-transparent bg-clip-text bg-gradient-to-r from-green-600 to-emerald-600 mt-2">
              AI-Generated Documents
            </span>
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            View examples of forms, certificates, emails, and structured data 
            automatically generated by Copilot.
          </p>
        </div>

        {/* Output Categories */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
          <div className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow">
            <FileText className="w-12 h-12 text-green-600 mb-4" />
            <h3 className="text-xl font-bold text-gray-900 mb-2">Registration Forms</h3>
            <p className="text-gray-600 text-sm mb-4">Auto-generated supplier registration forms with validation</p>
            <button className="text-green-600 font-semibold text-sm flex items-center space-x-1">
              <span>View Sample</span>
              <Download className="w-4 h-4" />
            </button>
          </div>

          <div className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow">
            <Mail className="w-12 h-12 text-blue-600 mb-4" />
            <h3 className="text-xl font-bold text-gray-900 mb-2">Email Templates</h3>
            <p className="text-gray-600 text-sm mb-4">Automated notification emails with personalization</p>
            <button className="text-blue-600 font-semibold text-sm flex items-center space-x-1">
              <span>View Sample</span>
              <Download className="w-4 h-4" />
            </button>
          </div>

          <div className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow">
            <Database className="w-12 h-12 text-purple-600 mb-4" />
            <h3 className="text-xl font-bold text-gray-900 mb-2">Structured Data</h3>
            <p className="text-gray-600 text-sm mb-4">Extracted and formatted JSON data from documents</p>
            <button className="text-purple-600 font-semibold text-sm flex items-center space-x-1">
              <span>View Sample</span>
              <Download className="w-4 h-4" />
            </button>
          </div>

          <div className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow">
            <Workflow className="w-12 h-12 text-orange-600 mb-4" />
            <h3 className="text-xl font-bold text-gray-900 mb-2">Workflow Diagrams</h3>
            <p className="text-gray-600 text-sm mb-4">Visual representations of approval processes</p>
            <button className="text-orange-600 font-semibold text-sm flex items-center space-x-1">
              <span>View Sample</span>
              <Download className="w-4 h-4" />
            </button>
          </div>

          <div className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow">
            <CheckCircle className="w-12 h-12 text-green-600 mb-4" />
            <h3 className="text-xl font-bold text-gray-900 mb-2">Certificates</h3>
            <p className="text-gray-600 text-sm mb-4">Registration certificates with digital signatures</p>
            <button className="text-green-600 font-semibold text-sm flex items-center space-x-1">
              <span>View Sample</span>
              <Download className="w-4 h-4" />
            </button>
          </div>

          <div className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-shadow">
            <FileText className="w-12 h-12 text-indigo-600 mb-4" />
            <h3 className="text-xl font-bold text-gray-900 mb-2">Summary Reports</h3>
            <p className="text-gray-600 text-sm mb-4">AI-generated document summaries and analysis</p>
            <button className="text-indigo-600 font-semibold text-sm flex items-center space-x-1">
              <span>View Sample</span>
              <Download className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Coming Soon Notice */}
        <div className="bg-white rounded-2xl shadow-lg p-8 text-center">
          <h3 className="text-2xl font-bold text-gray-900 mb-4">
            Detailed Output Examples Coming Soon
          </h3>
          <p className="text-gray-600">
            This section will showcase comprehensive examples of all AI-generated outputs.
          </p>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-900 text-white mt-16">
        <div className="max-w-7xl mx-auto px-6 py-6">
          <div className="flex items-center justify-between">
            <p className="text-sm text-gray-400">
              DLRRD Copilot Demo - Output Examples
            </p>
            <div className="flex items-center space-x-2 text-sm text-gray-400">
              <span>Step 5 of 6</span>
              <div className="w-32 h-2 bg-gray-700 rounded-full overflow-hidden">
                <div className="w-5/6 h-full bg-green-500"></div>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default OutputsPage;
